[package]
name = "rust_uom_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uom = { git = "https://github.com/iliekturtles/uom", version = "0.33.0" }
